# Generated by Django 3.2.6 on 2021-08-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='some-slug', max_length=500),
            preserve_default=False,
        ),
    ]
